name: github-actions-scan

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/*"

permissions:
  security-events: write
  # required for workflows in private repositories
  contents: read
  actions: read

jobs:
  zizmor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check if workflow files exist
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const fs = require('fs');
            const workflows = fs.readdirSync('.github/workflows').filter(file => file.endsWith('.yml') || file.endsWith('.yaml'));
            if (workflows.length > 0) {
              core.info("Workflows found, proceed with zizmor scan.");
              core.exportVariable('WORKFLOWS_EXISTS', 'true');
            } else {
              core.info("No workflows found, skip zizmor scan.");
            }

      - name: Install the latest version of uv
        if: env.WORKFLOWS_EXISTS == 'true'
        uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231 #v5.3.1
        with:
          enable-cache: false

      - name: Run zizmor
        if: env.WORKFLOWS_EXISTS == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -o pipefail
          uvx zizmor --pedantic --no-online-audits --format sarif . > zizmor.sarif

      - name: Upload SARIF file
        if: env.WORKFLOWS_EXISTS == 'true'
        uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5 # v3.28.11
        with:
          sarif_file: zizmor.sarif
          category: zizmor
